export { GeneralSection } from './GeneralSection'
export { AppearanceSection } from './AppearanceSection'
export type { Theme, AccentColor } from './AppearanceSection'
export { MachineSection } from './MachineSection'
export type { MachineConfig } from './MachineSection'
export { JoystickSection } from './JoystickSection'
export type { JoystickConfig, CncAction, AnalogAxis, AnalogMapping } from './JoystickSection'
export { UserAccountsSection } from './UserAccountsSection'
export type { UserAccount } from './UserAccountsSection'
export { CommandsSection } from './CommandsSection'
export type { Command } from './CommandsSection'
export { EventsSection } from './EventsSection'
export type { EventHandler, EventType, TriggerType } from './EventsSection'
export { AboutSection } from './AboutSection'

