export interface MacroVariable {
  type: 'header' | 'variable'
  text?: string // For headers
  value?: string // For variables (the actual code to insert)
}

export const macroVariables: MacroVariable[] = [
  { type: 'header', text: 'Wait until the planner queue is empty' },
  { type: 'variable', value: '%wait\n' },
  { type: 'header', text: 'User-defined global variables' },
  { type: 'variable', value: '%global.tool = Number(tool) || 0\n' },
  { type: 'header', text: 'Display a global variable using an inline comment' },
  { type: 'variable', value: '(tool=[global.tool])\n' },
  { type: 'header', text: 'Keep a backup of current work position' },
  { type: 'variable', value: '%X0=posx,Y0=posy,Z0=posz\n' },
  { type: 'header', text: 'Go to previous work position' },
  { type: 'variable', value: 'G0 X[X0] Y[Y0]\n' },
  { type: 'variable', value: 'G0 Z[Z0]\n' },
  { type: 'header', text: 'Tool change' },
  { type: 'variable', value: '%prevTool = Number(global.tool) || 0, global.tool = tool\n' },
  { type: 'header', text: 'Save modal state' },
  { type: 'variable', value: '%WCS=modal.wcs\n' },
  { type: 'variable', value: '%PLANE=modal.plane\n' },
  { type: 'variable', value: '%UNITS=modal.units\n' },
  { type: 'variable', value: '%DISTANCE=modal.distance\n' },
  { type: 'variable', value: '%FEEDRATE=modal.feedrate\n' },
  { type: 'variable', value: '%SPINDLE=modal.spindle\n' },
  { type: 'variable', value: '%COOLANT=modal.coolant\n' },
  { type: 'header', text: 'Restore modal state' },
  { type: 'variable', value: '[WCS] [PLANE] [UNITS] [DISTANCE] [FEEDRATE] [SPINDLE] [COOLANT]\n' },
  { type: 'header', text: 'Current work position' },
  { type: 'variable', value: '[posx]' },
  { type: 'variable', value: '[posy]' },
  { type: 'variable', value: '[posz]' },
  { type: 'variable', value: '[posa]' },
  { type: 'header', text: 'Set bounding box' },
  { type: 'variable', value: '%xmin=0,xmax=100,ymin=0,ymax=100,zmin=0,zmax=50\n' },
  { type: 'header', text: 'Bounding box' },
  { type: 'variable', value: '[xmin]' },
  { type: 'variable', value: '[xmax]' },
  { type: 'variable', value: '[ymin]' },
  { type: 'variable', value: '[ymax]' },
  { type: 'variable', value: '[zmin]' },
  { type: 'variable', value: '[zmax]' },
  { type: 'header', text: 'Macro parameters (prompt for input when macro runs)' },
  { type: 'variable', value: '; @param speed:number\n' },
  { type: 'variable', value: '; @param x:number\n' },
  { type: 'variable', value: '; @param y:number\n' },
  { type: 'variable', value: 'G0 X[x] Y[y] F[speed]\n' },
]
